name: movie_night
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  curved_navigation_bar: ^0.3.3
  dio: ^3.0.10
  flutter_swiper: ^1.1.6
  shared_preferences: ^0.5.10


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Teko_Bold
      fonts:
        - asset: assets/Teko-Bold.ttf

    - family: Teko_Medium
      fonts:
        - asset: assets/Teko-Medium.ttf

    - family: Teko_Regular
      fonts:
        - asset: assets/Teko-Regular.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
